#include "Events.h"

DEFINE_LOCAL_EVENT_TYPE(wxEVT_SET_MAP)
DEFINE_LOCAL_EVENT_TYPE(wxEVT_SEND_MSG)
DEFINE_LOCAL_EVENT_TYPE(wxEVT_SEND_STATUS)
IMPLEMENT_DYNAMIC_CLASS(wxSetMapEvent, wxNotifyEvent)
IMPLEMENT_DYNAMIC_CLASS(wxSendMsgEvent, wxNotifyEvent)
