#include "Events.h"

DEFINE_LOCAL_EVENT_TYPE(wxEVT_SET_MAP)
DEFINE_LOCAL_EVENT_TYPE(wxEVT_SEND_MSG)
DEFINE_LOCAL_EVENT_TYPE(wxEVT_SEND_SB)
DEFINE_LOCAL_EVENT_TYPE(wxEVT_CHANGE_DATA)
DEFINE_LOCAL_EVENT_TYPE(wxEVT_GAME_OVER)
IMPLEMENT_DYNAMIC_CLASS(wxSetMapEvent, wxNotifyEvent)
